function toBool(value) {
  if (value === null || value === undefined) return false;
  if (typeof value === "boolean") return value;
  const s = String(value).trim().toUpperCase();
  return s === "Y" || s === "1" || s === "TRUE";
}

function toNumber(value) {
  if (value === null || value === undefined || value === "") return null;
  const n = Number(value);
  return Number.isFinite(n) ? n : null;
}

function toDateString(value) {
  if (value === null || value === undefined) return null;
  const d = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(d.getTime())) return null;
  const ms = d.getUTCMilliseconds();
  if (ms === 0) {
    return d.toISOString().replace(/\.\d{3}Z$/, "");
  }
  return d.toISOString().replace("Z", "");
}

function mapShipmentHeaderRow(row) {
  return {
    InternalShipmentNum: toNumber(row.INTERNAL_SHIPMENT_NUM),
    AccessorialCharge: toNumber(row.ACCESSORIAL_CHARGE),
    ActualDeliveryDateTime: toDateString(row.ACTUAL_DELIVERY_DATE_TIME),
    ActualShipDateTime: toDateString(row.ACTUAL_SHIP_DATE_TIME),
    AllocateComplete: toBool(row.ALLOCATE_COMPLETE),
    AlternateEmailAddress: row.ALTERNATE_EMAIL_ADDRESS ?? null,
    AuthorizedEmplName: row.AUTHORIZED_EMPL_NAME ?? null,
    AuthorizedEmplTitle: row.AUTHORIZED_EMPL_TITLE ?? null,
    BaseFreightCharge: toNumber(row.BASE_FREIGHT_CHARGE),
    BolNumAlpha: row.BOL_NUM_ALPHA ?? null,
    Carrier: row.CARRIER ?? null,
    CarrierGroup: row.CARRIER_GROUP ?? null,
    CarrierService: row.CARRIER_SERVICE ?? null,
    CarrierType: row.CARRIER_TYPE ?? null,
    Company: row.COMPANY ?? null,
    Consolidated: toBool(row.CONSOLIDATED),
    ConsolidationAllowed: toBool(row.CONSOLIDATION_ALLOWED),
    ConsolidationDockLocArea: row.CONSOLIDATION_DOCK_LOC_AREA ?? null,
    ConsolidationDockLocPos: row.CONSOLIDATION_DOCK_LOC_POS ?? null,
    Containerized: toBool(row.CONTAINERIZED),
    CreationDateTimeStamp: toDateString(row.CREATION_DATE_TIME_STAMP),
    CreationProcessStamp: row.CREATION_PROCESS_STAMP ?? null,
    Customer: row.CUSTOMER ?? null,
    CustomerAddress1: row.CUSTOMER_ADDRESS1 ?? null,
    CustomerAddress2: row.CUSTOMER_ADDRESS2 ?? null,
    CustomerAddress3: row.CUSTOMER_ADDRESS3 ?? null,
    CustomerAttentionTo: row.CUSTOMER_ATTENTION_TO ?? null,
    CustomerCategory1: row.CUSTOMER_CATEGORY1 ?? null,
    CustomerCategory2: row.CUSTOMER_CATEGORY2 ?? null,
    CustomerCategory3: row.CUSTOMER_CATEGORY3 ?? null,
    CustomerCategory4: row.CUSTOMER_CATEGORY4 ?? null,
    CustomerCategory5: row.CUSTOMER_CATEGORY5 ?? null,
    CustomerCategory6: row.CUSTOMER_CATEGORY6 ?? null,
    CustomerCategory7: row.CUSTOMER_CATEGORY7 ?? null,
    CustomerCategory8: row.CUSTOMER_CATEGORY8 ?? null,
    CustomerCategory9: row.CUSTOMER_CATEGORY9 ?? null,
    CustomerCategory10: row.CUSTOMER_CATEGORY10 ?? null,
    CustomerCity: row.CUSTOMER_CITY ?? null,
    CustomerCountry: row.CUSTOMER_COUNTRY ?? null,
    CustomerEmailAddress: row.CUSTOMER_EMAIL_ADDRESS ?? null,
    CustomerFaxNum: row.CUSTOMER_FAX_NUM ?? null,
    CustomerName: row.CUSTOMER_NAME ?? null,
    CustomerPhoneNum: row.CUSTOMER_PHONE_NUM ?? null,
    CustomerPostalCode: row.CUSTOMER_POSTAL_CODE ?? null,
    CustomerResidentialFlag: toBool(row.CUSTOMER_RESIDENTIAL_FLAG),
    CustomerState: row.CUSTOMER_STATE ?? null,
    DateTimeStamp: toDateString(row.DATE_TIME_STAMP),
    Eccn: row.ECCN ?? null,
    ErpOrder: row.ERP_ORDER ?? null,
    ExportPort: row.EXPORT_PORT ?? null,
    ExportTaxId: row.EXPORT_TAX_ID ?? null,
    FreightBillTo: row.FREIGHT_BILL_TO ?? null,
    FreightBillToAddress1: row.FREIGHT_BILL_TO_ADDRESS1 ?? null,
    FreightBillToAddress2: row.FREIGHT_BILL_TO_ADDRESS2 ?? null,
    FreightBillToAddress3: row.FREIGHT_BILL_TO_ADDRESS3 ?? null,
    FreightBillToAttentionTo: row.FREIGHT_BILL_TO_ATTENTION_TO ?? null,
    FreightBillToCity: row.FREIGHT_BILL_TO_CITY ?? null,
    FreightBillToCountry: row.FREIGHT_BILL_TO_COUNTRY ?? null,
    FreightBillToEmailAddress: row.FREIGHT_BILL_TO_EMAIL_ADDRESS ?? null,
    FreightBillToFaxNum: row.FREIGHT_BILL_TO_FAX_NUM ?? null,
    FreightBillToName: row.FREIGHT_BILL_TO_NAME ?? null,
    FreightBillToPhoneNum: row.FREIGHT_BILL_TO_PHONE_NUM ?? null,
    FreightBillToPostalCode: row.FREIGHT_BILL_TO_POSTAL_CODE ?? null,
    FreightBillToState: row.FREIGHT_BILL_TO_STATE ?? null,
    FreightDiscount: toNumber(row.FREIGHT_DISCOUNT),
    FreightTerms: row.FREIGHT_TERMS ?? null,
    Ftz: row.FTZ ?? null,
    ImmediateNeedsNote: row.IMMEDIATE_NEEDS_NOTE ?? null,
    InDeletion: toBool(row.IN_DELETION),
    InterfaceRecordId: row.INTERFACE_RECORD_ID ?? null,
    IntermediateAddress1: row.INTERMEDIATE_ADDRESS1 ?? null,
    IntermediateAddress2: row.INTERMEDIATE_ADDRESS2 ?? null,
    IntermediateAddress3: row.INTERMEDIATE_ADDRESS3 ?? null,
    IntermediateAttentionTo: row.INTERMEDIATE_ATTENTION_TO ?? null,
    IntermediateCity: row.INTERMEDIATE_CITY ?? null,
    IntermediateConsignee: row.INTERMEDIATE_CONSIGNEE ?? null,
    IntermediateCountry: row.INTERMEDIATE_COUNTRY ?? null,
    IntermediateEmailAddress: row.INTERMEDIATE_EMAIL_ADDRESS ?? null,
    IntermediateFaxNum: row.INTERMEDIATE_FAX_NUM ?? null,
    IntermediateName: row.INTERMEDIATE_NAME ?? null,
    IntermediatePhoneNum: row.INTERMEDIATE_PHONE_NUM ?? null,
    IntermediatePostalCode: row.INTERMEDIATE_POSTAL_CODE ?? null,
    IntermediateState: row.INTERMEDIATE_STATE ?? null,
    InternalCarrierNum: toNumber(row.INTERNAL_CARRIER_NUM),
    InternalOrderNum: toNumber(row.INTERNAL_ORDER_NUM),
    InventoryLoadConfirmed: toBool(row.INVENTORY_LOAD_CONFIRMED),
    LastStatusUploaded: toNumber(row.LAST_STATUS_UPLOADED),
    LaunchNum: toNumber(row.LAUNCH_NUM),
    LaunchStep: row.LAUNCH_STEP ?? null,
    LeadingSts: toNumber(row.LEADING_STS),
    LeadingStsDate: toDateString(row.LEADING_STS_DATE),
    LeadingStsFailed: toBool(row.LEADING_STS_FAILED),
    LiabilityTerms: row.LIABILITY_TERMS ?? null,
    LicenseExpDate: toDateString(row.LICENSE_EXP_DATE),
    LoadingPier: row.LOADING_PIER ?? null,
    Locked: toBool(row.LOCKED),
    ManuallyEntered: toBool(row.MANUALLY_ENTERED),
    OrderType: row.ORDER_TYPE ?? null,
    Parties: row.PARTIES ?? null,
    PlannedDeliveryDateTime: toDateString(row.PLANNED_DELIVERY_DATE_TIME),
    PlannedShipDate: toDateString(row.PLANNED_SHIP_DATE),
    Priority: toNumber(row.PRIORITY),
    ProNumAlpha: row.PRO_NUM_ALPHA ?? null,
    ProcessStamp: row.PROCESS_STAMP ?? null,
    ProcessType: row.PROCESS_TYPE ?? null,
    QuantityUm: row.QUANTITY_UM ?? null,
    RejectionNote: row.REJECTION_NOTE ?? null,
    RequestedDeliveryDate: toDateString(row.REQUESTED_DELIVERY_DATE),
    RequestedDeliveryType: row.REQUESTED_DELIVERY_TYPE ?? null,
    Route: row.ROUTE ?? null,
    RoutingCode: row.ROUTING_CODE ?? null,
    ScheduledShipDate: toDateString(row.SCHEDULED_SHIP_DATE),
    ShipTo: row.SHIP_TO ?? null,
    ShipToAddress1: row.SHIP_TO_ADDRESS1 ?? null,
    ShipToAddress2: row.SHIP_TO_ADDRESS2 ?? null,
    ShipToAddress3: row.SHIP_TO_ADDRESS3 ?? null,
    ShipToAttentionTo: row.SHIP_TO_ATTENTION_TO ?? null,
    ShipToCity: row.SHIP_TO_CITY ?? null,
    ShipToCountry: row.SHIP_TO_COUNTRY ?? null,
    ShipToEmailAddress: row.SHIP_TO_EMAIL_ADDRESS ?? null,
    ShipToFaxNum: row.SHIP_TO_FAX_NUM ?? null,
    ShipToName: row.SHIP_TO_NAME ?? null,
    ShipToPhoneNum: row.SHIP_TO_PHONE_NUM ?? null,
    ShipToPostalCode: row.SHIP_TO_POSTAL_CODE ?? null,
    ShipToState: row.SHIP_TO_STATE ?? null,
    ShipmentId: row.SHIPMENT_ID ?? null,
    ShipperCode: row.SHIPPER_CODE ?? null,
    ShippingLoadNum: toNumber(row.SHIPPING_LOAD_NUM),
    ShiptoResidentialFlag: toBool(row.SHIPTO_RESIDENTIAL_FLAG),
    SingleItemCartons: row.SINGLE_ITEM_CARTONS ?? null,
    Stop: row.STOP ?? null,
    StopSequence: toNumber(row.STOP_SEQUENCE),
    StoreDistribution: row.STORE_DISTRIBUTION ?? null,
    TotalFreightCharge: toNumber(row.TOTAL_FREIGHT_CHARGE),
    TotalLbrEstimate: toNumber(row.TOTAL_LBR_ESTIMATE),
    TrailingSts: toNumber(row.TRAILING_STS),
    TrailingStsDate: toDateString(row.TRAILING_STS_DATE),
    TrailingStsFailed: toBool(row.TRAILING_STS_FAILED),
    TransportationMode: row.TRANSPORTATION_MODE ?? null,
    UnloadingPort: row.UNLOADING_PORT ?? null,
    UploadInterfaceBatch: row.UPLOAD_INTERFACE_BATCH ?? null,
    UserDef1: row.USER_DEF1 ?? null,
    UserDef2: row.USER_DEF2 ?? null,
    UserDef3: row.USER_DEF3 ?? null,
    UserDef4: row.USER_DEF4 ?? null,
    UserDef5: row.USER_DEF5 ?? null,
    UserDef6: row.USER_DEF6 ?? null,
    UserDef7: toNumber(row.USER_DEF7),
    UserDef8: toNumber(row.USER_DEF8),
    UserDef9: toNumber(row.USER_DEF9),
    UserDef10: toNumber(row.USER_DEF10),
    UserDef11: row.USER_DEF11 ?? null,
    UserDef12: row.USER_DEF12 ?? null,
    UserDef13: row.USER_DEF13 ?? null,
    UserDef14: row.USER_DEF14 ?? null,
    UserDef15: row.USER_DEF15 ?? null,
    UserDef16: row.USER_DEF16 ?? null,
    UserDef17DateTime: toDateString(row.USER_DEF17_DATE_TIME),
    UserDef18DateTime: toDateString(row.USER_DEF18_DATE_TIME),
    UserDef19DateTime: toDateString(row.USER_DEF19_DATE_TIME),
    UserDef20DateTime: toDateString(row.USER_DEF20_DATE_TIME),
    UserStamp: row.USER_STAMP ?? null,
    ValidatedLicense: row.VALIDATED_LICENSE ?? null,
    ValueEntered: toNumber(row.VALUE_ENTERED),
    VolumeEntered: toNumber(row.VOLUME_ENTERED),
    VolumeUm: row.VOLUME_UM ?? null,
    Warehouse: row.warehouse ?? null,
    WeightEntered: toNumber(row.WEIGHT_ENTERED),
    WeightUm: row.WEIGHT_UM ?? null,
    CarrierInfo: toNumber(row.INTERNAL_CARRIER_NUM),
  };
}

function mapShipmentHeaderRows(rows) {
  return rows.map(mapShipmentHeaderRow);
}

module.exports = {
  mapShipmentHeaderRow,
  mapShipmentHeaderRows,
};
